export const FETCH_TOURNAMENT_SUCCESS = 'FETCH_TOURNAMENT_SUCCESS'
export const FETCH_TOURNAMENT_FAILURE = 'FETCH_TOURNAMENT_FAILURE'
export const RESET_TOURNAMENT = 'RESET_TOURNAMENT'
export const ADD_TOURNAMENT_ON_STORAGE = 'ADD_TOURNAMENT_ON_STORAGE'